version: '3'
services:
  fluentd:
    # https://hub.docker.com/r/fluent/fluentd/
    # https://docs.fluentd.org/v0.12/articles/docker-logging-efk-compose
    # image: fluent/fluentd:v1.3
    build: ./fluentd
    links:
      - "elasticsearch"
    volumes:
      - ./fluentd/log:/fluentd/log
      # - ./fluentd/etc:/fluentd/etc
    # environment:
    #   - "FLUENTD_CONF=fluent.conf"
    ports:
      - "24224:24224"
      - "24224:24224/udp"

  elasticsearch:
    # https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.3
    expose:
      - 9200
      - 9300
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - "discovery.type=single-node"

  kibana:
    # https://www.elastic.co/guide/en/kibana/current/docker.html<Paste>
    image: docker.elastic.co/kibana/kibana:6.5.3
    # volumes:
    #   - ${pwd}/kibana.yml:/usr/share/kibana/config/kibana.yml
    links:
      - "elasticsearch"
    ports:
      - "5601:5601"
